service: deale-backend-test

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  addFavorite:
    handler: handler.add_favourite
    events:
      - http:
          path: add-favourite
          method: post
          cors: true

  listFavorites:
    handler: handler.list_favourites
    events:
      - http:
          path: list-favourites
          method: get
          cors: true

resources:
  Resources:
    FavoriteOrgsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: favourite_orgs
        AttributeDefinitions:
          - AttributeName: org_id
            AttributeType: N
          - AttributeName: favourite_org_id
            AttributeType: N
        KeySchema:
          - AttributeName: org_id
            KeyType: HASH
          - AttributeName: favourite_org_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        Tags:
          - Key: Name
            Value: DealeFavoriteOrgsTable

  Outputs:
    FavoriteOrgsTableArn:
      Description: "ARN de la tabla de DynamoDB para almacenar empresas favoritas"
      Value:
        Ref: "FavoriteOrgsTable"
